### ISSUE TITLE
Migrate from Python 2 to Python 3

### ISSUE THREAD

**Issue by MichaelTunnell** [slgobinath/uget-chrome-wrapper#12]
Hi,

I'm the Project Manager for uGet and I'd like to request a switch from Python 2 to Python 3.

I just found this project and I was very excited to see this and appreciate the work you've done on this thus far.

I know why it was made with 2.7 due to usage of things like PyPy but ultimately I think using Python 2 is something that should be avoided whenever possible. 

Do you have any plans to migrate to Python 3 when possible?

**Comment by slgobinath** [comment]
It's an amazing surprise to see you here :-)
Sure I will move it soon.

**Comment by MichaelTunnell** [comment]
> It's an amazing surprise to see you here :-)

I try to be attentive as much as possible.

>  Sure I will move it soon.

I am in no particular rush for it to be moved, I just wanted to make sure that it would be on the roadmap. :)

--------

I will be testing it myself soon to see how well it works, I am not a Chrome user so this has not been a vital issue for me but I know it has been for a lot of people so if this solves their issue then I'll be very happy to let people know about it.

**Comment by slgobinath** [comment]
Hi @MichaelTunnell,

I have switched to Python 3 in a [new branch](https://github.com/slgobinath/uget-chrome-wrapper/blob/uget-chrome-wrapper-2/uget-chrome-wrapper/bin/uget-chrome-wrapper). I will merge it to the master and update the documentation, once I've completed testing on various platforms.

Could you please provide a sample scenario where sending `--http-cookie-data` has impact on the download. I tried to send the cookie, but that doesn't make any difference on the behavior of `uget`. Also, I do not prefer to save the cookie to disk, and send it as file due to security reasons See [PR 8](https://github.com/slgobinath/uget-chrome-wrapper/pull/8).

Thanks

**Comment by MichaelTunnell** [comment]
> I have switched to Python 3 in a new branch. I will merge it to the master and update the documentation, once I've completed testing on various platforms.

Awesome!

> Could you please provide a sample scenario where sending --http-cookie-data has impact on the download. I tried to send the cookie, but that doesn't make any difference on the behavior of uget. 

Cookie Data is useful in situations where a user is trying to download a file that requires account authentication and checking previous authentication via cookies.

>Also, I do not prefer to save the cookie to disk, and send it as file due to security reasons See PR 8.

I am not sure what a good way to do this would be.

**Comment by slgobinath** [comment]
Hi @MichaelTunnell,
Doesn't uGet use the `--http-cookie-data`? I tried to pass session id using `uget-gtk --http-cookie-data='sessionId:xxx' <url>` but it has no impact. If you can clarify the input format, that would be helpful for me to implement it.

Thanks

**Comment by slgobinath** [comment]
`uget-chrome-wrapper` 2.0.0 (Migrated to Python 3) with new extension is released.

**Comment by slgobinath** [comment]
Hi @MichaelTunnell,

Sorry for contacting you here because I couldn't open a ticket in source forge. I have added cookie support to the extension. During the testing, I've noticed that uGet with aria2c does not use cookie file but uGet with curl plugin is working as expected. I am not sure whether I miss any configurations so I leave it to your concern.

Also, I'm pleased to inform you that Firefox extension is on the way. Still, FlashGot is the best option for Firefox users but this extension may be an alternative especially for those who are looking for WebExtension.

Plus one more request. Do you have any idea of providing Download Complete dialog as in IDM (may be an optional feature)? I really miss that feature to open the file/directory based on what I've downloaded.

Thanks

**Comment by MichaelTunnell** [comment]
> Sorry for contacting you here because I couldn't open a ticket in source forge.

Not sure why the SF account isnt accepting tickets, that's weird.

> I have added cookie support to the extension. During the testing, I've noticed that uGet with aria2c does not use cookie file but uGet with curl plugin is working as expected. I am not sure whether I miss any configurations so I leave it to your concern.

Very nice. Regarding the aria2 thing I am not sure what is up with that. I will talk to CH about it.

> I'm pleased to inform you that Firefox extension is on the way. Still, FlashGot is the best option for Firefox users but this extension may be an alternative especially for those who are looking for WebExtension.

Very cool and certainly something we might need in the future. I agree that FlashGot is overall the best option and has been for years but sadly there hasn't been any announcements that I have seen about them porting it to WebExtensions so perhaps in the future this could be a necessity for the project.

> Do you have any idea of providing Download Complete dialog as in IDM (may be an optional feature)? I really miss that feature to open the file/directory based on what I've downloaded.

I am not aware of that feature as I havent used IDM in over a decade. :) However, that does sound interesting but I don't know if that fits scope or not. Here are some questions I have for it.

1. Should it be done by checking what folder is for each download or defaulting to the category folder?
2. What if you have downloaded like 10 things, should it load 10 windows or just the last file's folder?
3. What if you download 10 files, 5 in two different folders but one of those files is in a unique folder? Potentially that is loading two main category folders and one file specific folder. That creates a lot of variation complexity.
4. How would it work with different file managers (this is more a general question though)

**Comment by slgobinath** [comment]
Hi,
I also haven't used IDM since I've switched to Linux. As far as I remember the dialog appears only after downloading one file triggered from the browser. If there are more than one concurrent downloads, then that many dialogs will appear. But the way uGet handles multiple downloads is different from IDM.

What I have in my mind as a feasible solution that answers all your questions is a dialog with a list of checkbox items (Better to provide shortcuts for selected item as current uGet Enter to open file and Shift + Enter to open the directory)
![uget](https://cloud.githubusercontent.com/assets/4003168/25914107/1b806fe6-358b-11e7-9039-291d34c3e300.png)

I hope this solution works well with a single file as well as multiple files downloaded to different locations. How to open a file or folder can be exactly same as how uGet main window behaves. The folder must be where the file is not based on category.
