### ISSUE TITLE
No Uget option in download dialog

### ISSUE THREAD

**Issue by alleyoopster** [slgobinath/uget-chrome-wrapper#22]
Uget 2.09 Wrapper 2.0.4 Firefox  55.0.2 (64-bit) OS Manjaro 

Uget and wrapper both detected by plugin but when I try to download a file, Uget does not appear as an option in the download dialog box for Firefox. I only see the choices of "Open with" and "Save file"

**Comment by slgobinath** [comment]
It does not work as Flashogot.
Select the save file option and uGet should interrupt the download. However, I do experience some issues with catching & skipping some downloads (Works well with Chrome but some problems in Firefox) and will fix them asap.

**Comment by alleyoopster** [comment]
OK thanks for that. I tried another site and it is working there, but always fails on a google drive download. I am using this [link](https://drive.google.com/file/d/0B8ENyWhpePB8Mzc0NjVJMlZ1bEk/view)

**Comment by slgobinath** [comment]
Google Drive is ignored purposefully at the extension level because it has some problems with external download managers. See this Ask Ubuntu question:[ How to download large Google Drive file with resume support in Ubuntu?](https://askubuntu.com/questions/770753/how-to-download-large-google-drive-file-with-resume-support-in-ubuntu)
However, you can try the `Download with uGet` option from the right-click menu even though it is not guaranteed to work with uGet.

**Comment by alleyoopster** [comment]
OK cool. I can work around the google issue. I'll just get copy the download link as detailed in that link. thanks

**Comment by slgobinath** [comment]
Great :-)
I am closing this issue.
