### ISSUE TITLE
Doesn't work all the time in Vivaldi

### ISSUE THREAD

**Issue by NovaViper** [slgobinath/uget-chrome-wrapper#25]
For some reason, the extension doesn't start up uGet in Vivaldi with (almost) every link I've tried. This same thing happens on both my desktop and laptop.

Both PCs have Vivaldi 1.11.917.39 (Stable channel) (32-bit), uGet 2.0.10, Python 3.6.2, uGet Wrapper 2.0.4, uGet Wrapper Extension 2.0.7, and running Windows 10 Home 64-bit.

Some of the places I've tried are Curse/CurseForge (for Minecraft), Github, SourceForge, and Google Drive

**Comment by slgobinath** [comment]
Hi,
I will test it in my virtual machine and let you know.

**Comment by slgobinath** [comment]
Hi,

Based on my testing, I couldn't find any problems. However, please note that uGet Integration extension does not interrupt Google Drive links purposefully. (For more details: [How to download large Google Drive file with resume support in Ubuntu?](http://askubuntu.com/questions/770753/how-to-download-large-google-drive-file-with-resume-support-in-ubuntu).

According to my testing, at least GitHub and Sourceforge should work.

For a basic test, could you please try to download Notepad++ application from their [official site](https://notepad-plus-plus.org/download/v7.4.2.html) and let me know if it works or not.

**Comment by NovaViper** [comment]
I played around with the settings and got those websites to work! But.. I do notice that whenever I download files from Google Drive, it seems to convert it to a bunch of letters with no format at the end

**Comment by slgobinath** [comment]
Thanks for the update.
I am closing this issue.

**Comment by NovaViper** [comment]
What about the downloads from Google? The same thing happens whenever I download from MEGA or any Google website

**Comment by slgobinath** [comment]
If a link contains either of these: `//docs.google.com/`, `googleusercontent.com/docs` the extension will skip it (See [background.js](https://github.com/slgobinath/uget-chrome-wrapper/blob/master/extension/background.js#L484).
Further, some cloud storages stream the file to download instead of providing direct URLs. In such cases, the filename reported by the browser is either `0` or `-1` which is smaller than the minimum file size to interrupt. Therefore, the extension ignores them as well.
I also faced such issues when I use my inter-university cloud storage and even if I copy and provide that URL, uGet is unable to download the file (due to the same streaming reason). So I guess it is better to let the browsers to handle those files instead of interrupting and failing to download.

**Comment by MichaelTunnell** [comment]
> "The same thing happens whenever I download from MEGA"

Support for MEGA in uGet is actually in development. :)

**Comment by NovaViper** [comment]
Cool but.. what about all google domain websites?

**Comment by MichaelTunnell** [comment]
> what about all google domain websites?

That would require building support for Google Authentication API which is not something on our todo list at the moment. I won't rule it out but we have other plans that are taking priority for sure.

**Comment by NovaViper** [comment]
Cool, glad to know that you guys that it's something considered ^_^
