### ISSUE TITLE
Settings won't save

### ISSUE THREAD

**Issue by clessley** [slgobinath/uget-chrome-wrapper#37]
One machine Linux 17.10, one machine Windows 7 both running Firefox 56+.

The file type and minimum file size options do not persist after saving. They work until the next session then revert back to default, ie 300.

Can they be manually hard coded, 800 seems to be my sweet spot for min. file size for easier PDF viewing.

**Comment by DanaMW** [comment]
He currently uses storage that is cleared when your browser is. He has it set to change to more protected memory in the next version

**Comment by slgobinath** [comment]
Thanks, @DanaMW.
I have fixed this problem in the PR https://github.com/slgobinath/uget-chrome-wrapper/commit/0b262805eaa540417440959483aef8f8ec391d83.
Note that I am using `storage.sync` so that the extension properties will be synchronized across devices.

**Comment by DanaMW** [comment]
Nice thank you for your work. Umm I was wondering how hard it would be to put a toggle in to allow me to catch all downloads I have to delete the handler once a day or so

**Comment by DanaMW** [comment]
I used flashgot all these years and had it set to catch all, I don't use the browser to do any file sorting I have other methods so this for me is very aggravating when the browser catches so many files.

**Comment by NovaViper** [comment]
I'm having this same issue on Windows 10 with Vivaldi. The recent 2.0.6 wrapper and the 2.1.0 extension update makes the settings not save nor does the extension interrupt downloads anymore

**Comment by slgobinath** [comment]
@NovaViper I couldn't reproduce this on my Linux machine with Vivaldi but will try on my Windows VM and let you know.

@clessley you reported this problem for the 2.0.9 version. Do you still have this issue?

**Comment by clessley** [comment]
Issue on Linux is 2.1.0.

**Comment by slgobinath** [comment]
Hi,
Those who report settings won't change in Firefox, please check the architecture of your system and Firefox. I also got this issue in my Windows 10 VM (**64 bit**) running Firefox **32 bit**. After replacing the Firefox by the 64bit version, the problem has been fixed.

I did not get this problem in my Ubuntu 17.10 VM because already I had 64 bit Firefox there.

FYI: The Firefox web installer always installs the 32 bit version (at least in my case). Follow this guideline to install Firefox 64bit on Windows: [How to switch from 32-bit to 64-bit Firefox](https://support.mozilla.org/en-US/kb/switch-32-bit-64-bit)

> nor does the extension interrupt downloads anymore

I also observed this problem in Windows (not in Linux). the fix is starting uGet manually (or by adding it to the startup) before Firefox.
The problem is when the Python script terminates, it terminates the uGet it has started.

**Comment by clessley** [comment]
10-30-2017 uget-chrome-wrapper updated on the Ubuntu Mate 17.10 machine which is 64 bit. The settings are now retained across browser restarts and machine reboots. The extension reads as 2.1.0. Thanks.
