### ISSUE TITLE
The linux installation script still points to v2.0.5

### ISSUE THREAD

**Issue by bobafetthotmail** [slgobinath/uget-chrome-wrapper#38]
**install_uget_chrome_wrapper.sh** still downloads the v2.0.5 version.

editing the script manually to use links pointing to v2.0.6 folder works fine.

While you are at it, what about making a "latest" folder instead of "v2.0.6" for the script?

This way people can update the uget-chrome-wrapper by just running again the same script they downloaded before, and you don't need to remember to update install_uget_chrome_wrapper.sh every time you update the version.

**Comment by slgobinath** [comment]
Your suggestion makes sense.
However, we cannot create all the releases to `latest` because it will not help tracking version changes. The Arch build also requires new releases based on version.
I have updated the script to 2.0.6 for the moment but I will find out a way to use the same script to update `uget-chrome-wrapper`.

**Comment by bobafetthotmail** [comment]
Ok, thanks.

**Comment by slgobinath** [comment]
Hi,
Now the script is updated with the commit https://github.com/slgobinath/uget-chrome-wrapper/commit/d54a69e4468ec699df0c01603d33c840967f0b67 to automatically check the latest version and to install it.

**Comment by bobafetthotmail** [comment]
Nice!
Thanks again :)
