### ISSUE TITLE
Doesn't work in firefox quantum

### ISSUE THREAD

**Issue by SeunLanLege** [slgobinath/uget-chrome-wrapper#43]
What the title says

**Comment by slgobinath** [comment]
Hi,
Could you please share your operating system and the architecture of both Firefox and OS (64 bit or 32 bit) because I am already using it with my Firefox Quantum on Linux Mint and Arch.

Thanks

**Comment by SeunLanLege** [comment]
Ubuntu 16.04, Firefox Nightly 59.0a1

**Comment by slgobinath** [comment]
Is your Firefox 32 bit or 64 bit? (You can check this in the Help --> About Firefox dialog)

**Comment by SeunLanLege** [comment]
64bit

**Comment by slgobinath** [comment]
Then it seems to be a new issue. I will have a look at it and let you know.

Thanks

**Comment by perfectcream** [comment]
Hi! I'm using Firefox Quantum (57.0) x64 on Microsoft Windows [version 10.0.16299.64] (a.k.a. Windows 10 Fall Creators Update 1709) with the same problem. 

I think this problem may be related to these issues below:

* pip issues UnicodeDecodeError on Windows 10 for Russian language #4251
https://github.com/pypa/pip/issues/4251

* Add one more fail-safe when decoding console to str in Py3 by sakurai-youhei · Pull Request #4310 · pypa/pip
https://github.com/pypa/pip/pull/4310

**Comment by prpdesigns** [comment]
Kubuntu 14.04 64bit, Firefox 57.0 64bit doesn't work either

**Comment by MichaelTunnell** [comment]
It works fine for me in KDE Neon using Extension v2.1.0 and uGet 2.0.10

Here is what I think the issue is.

@SeunLanLege I think your issue is the usage of Firefox Nightly, try it in a different version of Firefox please so we can get more data on the issue.

@perfectcream I think your issue is the usage of Windows 10. I am not sure how the extension locates uGet on Windows. @slgobinath could you clarify how it detects it?

@prpdesigns your issue could be the Kubuntu 14.04 part as there has been a ton of changes in KDE Plasma since that release. What version of uGet are you using on your system?

**Comment by DanaMW** [comment]
It works on windows 10. In chrome Firefox and Vivaldi. I use wrapper 206. the uget extension and the beta Uget 2.1.6

**Comment by prpdesigns** [comment]
@MichaelTunnell uGet 2.0.10, extension 2.1.0

**Comment by SeunLanLege** [comment]
More details on it though - Right clicking and selecting `Download with uget` works fine.

but it doesn't intercept downloads.

**Comment by slgobinath** [comment]
Hi @MichaelTunnell and @perfectcream,
In Windows uget bin directory must be added to the `PATH` variable. See the installation guide for Windows and this [screenshot](https://raw.githubusercontent.com/slgobinath/uget-chrome-wrapper/master/build/windows/add_uget_to_path.png).

@SeunLanLege if `Download with uget` is working the problem is with the extension. However, I couldn't reproduce it in my system with Firefox Nightly 59.0a1 (2017-11-17) (64-bit). I will investigate further and let you know. One more question.
Do you get the `Info: Found uGet and uget-chrome-wrapper` message in the extension dialog(Click on the extension icon)? Also double check the extension setings. (I would recommend delete all the input fields except the minimum file size to interrupt. Set the minimum file size to interrupt to `-1` and see what happens)

**Comment by perfectcream** [comment]
Hi! @slgobinath, @MichaelTunnell and @DanaMW,

After I add the path of uGet to System Environment Variables **PATH**, I can download files with right click on context menu, thank you so much :)

But I can't replaces default download manager by uGet Download Manager (namely intercept downloads).

As you can see in screenshot: [uGet Integration](https://imgur.com/a/ZYalm) 

It can found `uGet and uget-chrome-wrapper`, but when I click link to download file ([HWiNFO](https://www.fosshub.com/HWiNFO.html) for example), Firefox 57.0 still uses default download manager to download files. (I had try to set the `minimum file size to interrupt` to **-1**, and got the same result.)

Thank you for all your assistance.

**Comment by perfectcream** [comment]
Hi @slgobinath, 

I had try another PATH setting, it works! I can replaces default download manager by uGet Download Manager now.

How to reproduce it?

1. extra and copy uGet files in `C:\uGet` not C:\Program Files (x86)\uGet\
2. set the path of uGet in  System Environment Variables **PATH** to `C:\uGet\bin`
3. install Python 3.4 or latest
4. download and install uget-chrome-wrapper_2.0.6.0.exe
5. install the uGet Integration extension and restart Firefox 57.0

I think this problem may origins in how the program deal with " (x86)" string in the path.

**Comment by slgobinath** [comment]
Hi @perfectcream,
Thanks for the update. I will update the webpage soon including your steps to follow.

**Comment by DanaMW** [comment]
When I first started using this fine setup I had to delete handlers.json in the Firefox profile folder to get a fresh start. After that uget started (for the most part) catching downloads. Firefox will recreate handlers.json on start up but if you have custom download handling in Firefox make notes of it before you delete. Maybe this will help you as it did me.

**Comment by SeunLanLege** [comment]
@slgobinath  just tried setting the minimum download size to -1. Still didn't work.

yes i can see `info: found uget and uget-chrome-wrapper`

**Comment by prpdesigns** [comment]
@DanaMW @slgobinath @MichaelTunnell deleting the **handlers.json** file worked for me.

Thanks!

**Comment by slgobinath** [comment]
Hi @perfectcream,
Could you please share the location of `handlers.json`.

@SeunLanLege could you please try this solution.

Thanks.

**Comment by SeunLanLege** [comment]
@slgobinath just deleted my `handlers.json` in `home/.mozilla/firefox-trunk/(some wierd folder name)/handlers.json`

and it works perfectly, thanks everyone :raised_hands:

**Comment by slgobinath** [comment]
Thanks to all.
I will update the README it as a known issue.

**Comment by DanaMW** [comment]
handlers.json is in the users FF profile folder for the record. And thank YOU for your work.

**Comment by perfectcream** [comment]
Hi @slgobinath,

My handlers.json can be located at:
`c:\Users\USER_NAME\AppData\Roaming\Mozilla\Firefox\Profiles\xxxxxxxx.default\handlers.json`

**USER_NAME** may include unicode characters.
**xxxxxxxx** is random string.

Thanks a lot :)
