### ISSUE TITLE
Setting uGet directory in the options dialog

### ISSUE THREAD

**Issue by AirQuick** [slgobinath/uget-chrome-wrapper#46]
Feature request (for Windows).

Putting the uGet program path into `PATH` environment variable is cumbersome. Also, since there are a lot of DLLs in the uGet bin directory, I'm a bit reluctant to include it in `PATH`.

So, it would be nice if we can specify the uGet program dir (such as `c:\program files (x86)\uget`) in the options dialog. Then we won't have to touch `PATH` at all. (Putting Python into `PATH` is already not necessary today.)

**Comment by slgobinath** [comment]
Hi,
I am little against to adding an option in the extension because it is required only in Windows and it will let people specify different locations. There is more chance of asking support for other download managers too.
There is a discussion going on with uGet Team on providing an installer for uGet that will add a shortcut to uGet in system PATH. If that works, we can overcome this problem.
WDYT?

**Comment by AirQuick** [comment]
Hi Gobinath,
Interesting. Can you point me to the discussion thread about the installer?

Anyway, I'm afraid the installer would help the portable mode introduced in uGet 2.0.6.

**Comment by slgobinath** [comment]
Hi,
The discussion is in mail thread. The portable installation will be still available but the installer will add the uget-gtk.exe to PATH so the wrapper can easily identify it.

**Comment by slgobinath** [comment]
This problem has been fixed in current development version with the support of a new [uGet Windows Installer](https://github.com/ugetdm/uget-windows-installer) which is not released yet.

FYI: Please note that uget-chrome-wrapper is merged with uGet. https://github.com/slgobinath/uget-chrome-wrapper/issues/53
