### ISSUE TITLE
is  "sudo mkdir -p /usr/lib64/mozilla/native-messaging-hosts" necessary?

### ISSUE THREAD

**Issue by youxiaojie** [slgobinath/uget-chrome-wrapper#47]
I use a newly installed debian 9.3 64 bit,with the orginal 64bit firefox.I just found  /usr/lib64/mozilla/native-messaging-hosts directory and copy the json file. "#cp conf/com.javahelps.ugetfirefoxwrapper.json /usr/lib/mozilla/native-messaging-hosts/"  and then "#cp bin/uget-chrome-wrapper /usr/bin/; chmod +x /usr/bin/uget-chrome-wrapper" restart firefox the firefox extension works ok. 

so I doubt  whether it is necessary that " sudo mkdir -p /usr/lib64/mozilla/native-messaging-hosts" and download com.javahelps.ugetfirefoxwrapper.json into it"

**Comment by slgobinath** [comment]
Hi,

It is not necessary if everything works fine. I had some issues reported related to the Firefox architecture and system architecture. In such cases only, `lib64` was required.

However, I create all the required files to hide the complexity from the users. Otherwise, I have to ask them to trial and test each file.
