### ISSUE TITLE
Filter file extensions and websites

### ISSUE THREAD

**Issue by KaKi87** [slgobinath/uget-chrome-wrapper#49]
Hi,

I would like to suggest some improvements in filter settings.

## Filter file extensions

For example, if I do this :
![screenshot](https://i.goopics.net/nEEeK.png)

Yes, all pdf files will be ignored. But if I want to download a file which has "pdf" in the title, but which is actually not a pdf file, it will ignore it, and that's a problem.

So I would like an option for filtering file extensions only.

## Filter websites

There are some websites I would like to not use uGet at all, so I would like them to be ignored.
It could be `abc.xyz/*` or `*.abc.xyz` or `abc.xyz/foo/bar/*` or anything like that.

Thanks !

**Comment by slgobinath** [comment]
Makes sense. I went that way because sometimes file name may not be available or may not contain `.pdf`.
I will try to fix it using application type.

**Comment by KaKi87** [comment]
Or with regex `\.([aA-zZ0-9])$`

**Comment by slgobinath** [comment]
Fixed with https://github.com/ugetdm/uget-extension/commit/0b56175f7531e8148d293d4b787f1e6b44c0c8bd.
Note that responses may not have content-type or MIME type. In such cases, overriding minimum file size by content type will not work.

Also note https://github.com/slgobinath/uget-chrome-wrapper/issues/53
