### ISSUE TITLE
Google Doc files cannot be downloaded via uGet

### ISSUE THREAD

**Issue by doylefermi** [slgobinath/uget-chrome-wrapper#6]
Please add feature to add exceptions in uget-chrome-wrapper to not to download from specific URLs.

**Comment by slgobinath** [comment]
Google Doc is already skipped by uget-chrome-wrapper (See the issue https://github.com/slgobinath/uget-chrome-wrapper/issues/2). Please make sure that you have the uGet Integration extension 1.1.1 or latest.

**Comment by doylefermi** [comment]
Screenshare
![output](https://cloud.githubusercontent.com/assets/8755940/19875794/dba58b20-9ff5-11e6-8e4e-eebd5c114dd7.gif)

**Comment by slgobinath** [comment]
Thanks for reporting this bug. A quick fix will be released soon.

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/uget-chrome-wrapper/commit/354cdd4e3b53f25221051a875299ae8de68b7fb5
Upgrade the Chrome Extension to 1.1.2 or latest (A new version of uget-chrome-wrapper also released with a patch for another bug)
See the release [v1.3](https://github.com/slgobinath/uget-chrome-wrapper/releases/tag/v1.3)

**Comment by doylefermi** [comment]
Is it possible to generalize the call. Instead of passing to uGet alone, passing to aria2c will also do. Something as a replacement for [Flashgot](https://flashgot.net/) for firefox

**Comment by slgobinath** [comment]
@doylefermi It is possible but uget-chrome-wrapper targets uGet alone. I do not have any idea of generalizing this as Flashgot because it requires more testing and development effort. I see uGet as a potential download manager for Linux and thats the only reason to support uGet. However I +1 your suggestion and volunteers are welcomed to fork this project and develop such a generalized extension.

To change the targeted download manager, you have to change the command line call @ https://github.com/slgobinath/uget-chrome-wrapper/blob/master/uget-chrome-wrapper/bin/uget-chrome-wrapper#L77
