### ISSUE TITLE
Extension opens uget-chrome-wrapper.py instead of executing it on Windows 10

### ISSUE THREAD

**Issue by flawiddsouza** [slgobinath/uget-chrome-wrapper#9]
As the title says, chrome opens uget-chrome-wrapper.py instead of executing it whenever I choose "Download with uGet". uget-chrome-wrapper.py just gets opened in my code editor.

**Comment by doylefermi** [comment]
Hope you have followed the [tutorial](https://slgobinath.github.io/uget-chrome-wrapper/#windows) and is python working?

**Comment by flawiddsouza** [comment]
Yes but I think python needs to be associated with .py files for this to work. My .py files are associated with my code editor. Associating them with the python executable would make it really annoying to open them when you're coding in Python. Any solution? In Windows, python files need to executed by prepending py or python before the python files.

**Comment by slgobinath** [comment]
I will add a fix for this issue soon.

**Comment by slgobinath** [comment]
This problem seems to be hard to fix. Introducing a bat file to call python explicitly or, executing python with the script as argument directly from the chrome does not work. Only possible way would be converting the python script to exe or writing a native messaging client in any other languages which produce compiled exe file (Eg: C, C++, .Net). Since uGet Chrome Wrapper targets Linux and the development effort is high for this minor issue, this issue won't be fixed.

**Comment by flawiddsouza** [comment]
That's disappointing but understandable.

**Comment by slgobinath** [comment]
Hi @flawiddsouza,

I have changed the way to connect the host file in the latest version [v2.0.4](https://github.com/slgobinath/uget-chrome-wrapper/releases/tag/v2.0.4). This time I use a bat file to call Python so it should help you to resolve the problem.

Note: Please make sure that Python (we use Python 3 now) is added to the system PATH.
